### ISSUE TITLE
QIF splits

### ISSUE THREAD

**Issue by pekatete** [viceroypenguin/Making.Cents#2]
Not an issue really - just wanted to pick your brain but cannot find a discussion on the project.
I refer to https://github.com/viceroypenguin/Making.Cents/commit/adab96b273e36b8075a91806d148a14c2d30517c where you finally figured out how stock splits work in QIF., how would the QIF Q entry be for a 1 -> 2 (forward?) split of 120 shares to 240 shares? Would it be 24 or 240?

**Comment by viceroypenguin** [comment]
It would actually be `20`. It's a 2-1 split, so normally the multiplier is 2 (120 * 2 = 240). But then Quicken uses 10* the multiplier, so it would be 2 * 10 = 20.

**Comment by pekatete** [comment]
Thanks. Quicken surely made that convoluted, a "split" from 120 to 240 shares having a quantity of 20
